config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index'
  get 'signup/index'
  

  resources :doctors
  resources :patients
  resources :appointments, only: [:new, :create, :destroy, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates_presence_of :name, :description

  has_many :appointments, dependent: :destroy
  has_many :patients, through: :appointments

end

app/models/patient.rb
class Patient < ApplicationRecord

  validates_presence_of :name

  has_many :appointments, dependent: :destroy
  has_many :doctors, through: :appointments

end

app/models/user.rb
class User < ApplicationRecord
    @user = User.all
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
    @doctors = Doctor.all.map { |d| [d.name, d.id] }
    @patients = Patient.all.map { |t| [t.name, t.id]  }
    @appointment = Appointment.new
  end

  def index
    @appointments = Appointment.all
  end

  def create
   @appointment = Appointment.new(appointment_params)

    if @appointment.save
      redirect_to appointments_path, notice: 'Appointment was successfully created.'
    else
      render :new
    end
  
  end

  def destroy
    appointment = Appointment.find(params[:id])
    appointment.destroy
    flash[:success] = 'Appointment Deleted!'
    redirect_to doctor_path(appointment.doctor_id)
  end

  private

  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id)

  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]
  def index
    @doctors = Doctor.all
  end

  def new
    @doctors = Doctor.new
  end

  def show
  end

  def edit
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to @doctor, notice: 'Doctor was successfully created.'
    else
      render :new
    end
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: 'Doctor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_url, notice: 'Doctor was successfully deleted.'
  end

  private

    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name, :description)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def show
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient, notice: 'Patient was successfully created.'
    else
      render :new
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to patients_path, notice: 'Patient was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_url, notice: 'Patient was successfully deleted.'
  end

  private

    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:name, :description)
    end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  def index
  end

  def create
    user = User.create(user_params)
    SignupMailer.new_signup(user).deliver
    redirect_to root_path
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/appointments/new.html.erb
<h1> Add An Appointment </h1>
<hr />

<%= form_for @appointment do |f| %>
  <%= f.select :doctor_id, options_for_select(@doctors) %>
  <%= f.select :patient_id, options_for_select(@patients) %>


  <%= f.submit nil, class: 'btn' %>
<% end %>

<hr />
<%= link_to 'All Doctors', doctors_path %> |
<%= link_to 'All Patients', patients_path %>

app/views/doctors/_form.html.erb
<%= form_for(doctor) do |f| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% doctor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Editing Doctor</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/index.html.erb
<h1<h1>Doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.description %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br />

<%= link_to 'New Doctor', new_doctor_path %> |

<%= link_to 'Add New Appointment', new_appointment_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctors %>

app/views/doctors/show.html.erb
<h1>Doctor: <%= @doctor.name %> </h1>

<% unless @doctor.description.empty? %>
    <p>
      <strong>Description:</strong>
      <%= @doctor.description %>
    </p>
    <hr />
<% end %>

<% if @doctor.patients.any? %>
    <h5> Patients </h5>
    <ul>
        <% @doctor.appointments.each do |appointment| %>
          <li>
            <%= appointment.patient.name %> -
            <%= link_to 'Remove', appointment_path(appointment), method: :delete, data: {confirm: 'Really remove this appointmen?'} %>
          </li>
        <% end %>
    </ul>
<% else %>
  <h5>No Appointments Found</h5>
<% end %>

<%= link_to 'All doctors', doctors_path %> |
<%= link_to 'Edit', edit_doctor_path(@doctor) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorOffice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Doctors office</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li> <%= link_to 'Doctors', doctors_path %> </li>
          <li> <%= link_to 'Patients', patients_path %> </li>
          <li> <%= link_to 'Add Appointment', new_appointment_path %> </li>
        </ul>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>

    <div class='container'>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for(patient) do |f| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<h1>Patient: <%= @patient.name %> </h1>


<% if @patient.doctors.any? %>
    <h5> Doctors </h5>
    <ul>
        <% @patient.appointments.each do |appointment| %>
          <li>
            <%= appointment.patient.name %> -
            <%= link_to 'Remove', appointment_path(appointment), method: :delete, data: {confirm: 'Really remove this appointmen?'} %>
          </li>
        <% end %>
    </ul>
<% else %>
  <h5>No Appointments Found</h5>
<% end %>

<%= link_to 'All Patients', patients_path %> |
<%= link_to 'Edit', edit_patient_path(@patient) %>

app/views/signup/index.html.erb
<h1>Signup#index</h1>
<p>Find me in app/views/signup/index.html.erb</p>